# Generated by Django 5.2.7 on 2025-11-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='once', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger'), ('both', 'Both')], max_length=20),
        ),
    ]
