# Generated by Django 5.2.7 on 2025-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_available_seats_trip_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='flexibility_after_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='flexibility_before_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
