# Generated by Django 5.2.7 on 2025-11-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_flexibility_after_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_matches', to='trips.trip')),
                ('passenger_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_matches', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('driver_trip', 'passenger_trip')},
            },
        ),
    ]
